on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/workflows/build_iso.yml"
  merge_group:
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/radulinux
  IMAGE_TAG: 40

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_image:
    runs-on: ubuntu-latest
    name: Build image
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ghcr.io/${{ github.repository_owner }}
      - name: Pull kmods image
        run: |
          podman pull ${{ steps.registry_case.outputs.lowercase }}/kmods:${{ env.IMAGE_TAG }}
      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          containerfiles: |
            ./Containerfile
      - name: Push To GHCR
        uses: Wandalen/wretry.action@v3.4.0
        id: push
        if: github.event_name != 'pull_request'
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          action: redhat-actions/push-to-registry@v2
          attempt_limit: 3
          attempt_delay: 15000
          with: |
            image: ${{ steps.build_image.outputs.image }}
            tags: ${{ steps.build_image.outputs.tags }}
            registry: ${{ steps.registry_case.outputs.lowercase }}
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Sign container
      - uses: sigstore/cosign-installer@v3.5.0
        if: github.event_name != 'pull_request'

      - name: Sign container image
        uses: EyeCantCU/cosign-action/sign@v0.2.2
        if: github.event_name != 'pull_request'
        with:
          containers: ${{ env.IMAGE_NAME }}
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          signing-secret: ${{ secrets.COSIGN_PRIVATE_KEY }}
          tags: ${{ steps.push.outputs.outputs && fromJSON(steps.push.outputs.outputs).digest }}
